/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vtenda;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAW221
 */
public class PaListarProducto extends javax.swing.JDialog {
    
    public static int salir = 0;
    public DefaultTableModel modelo;
    
    public PaListarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Image icono = Toolkit.getDefaultToolkit().getImage(VTenda.dirIMG);
        this.setIconImage(icono);
        
        this.setLocationRelativeTo(null);
        
        String cabecera[]={"Articulo", "Nombre", "Categoria", "Stock", "Sin IVA", "IVA", "Con IVA"};
        String datos[][]={};
        
        modelo = new DefaultTableModel(datos, cabecera);
        this.productos.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLCodigoProducto = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        errores = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTable();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VTenda - Productos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLCodigoProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCodigoProducto.setText("Código Producto:");

        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(204, 204, 204));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        errores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(errores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(errores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productos.setEnabled(false);
        jScrollPane1.setViewportView(productos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addContainerGap())
        );

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        try{
            /*Limpar Lista*/
            int a=modelo.getRowCount();
            
            for (int i = 0; i < a; i++) {
                modelo.removeRow(0);
            }
            
        }catch(Exception ex){
            System.err.println(ex.getMessage());
        }
        
        try{
            
            String cod, nome, Categoria, Stock, SinIVA, iva, ConIVA;
            
            /*Conexion contra DB*/
            db.consultas con = new db.consultas();
            
            System.out.println("Introduciendo productos en lista");
             
            /* contador productos */
            int cont = 0;
            
            /* Consulta Productos */
            ResultSet rs = con.select("productos", "1");
            
            while(rs.next()){
                
                cont++;
                
                ResultSet rsaux = con.select("categorias", "1 ORDER BY 'cod' ASC");
                
                String NombreCategoria = "";
                
                while(rsaux.next()){
                    
                    if(rs.getInt("codCategoria") == rsaux.getInt("cod")){
                        NombreCategoria = rsaux.getString("nombre");
                    }
                    
                }
                
                Productos p1 = new Productos(rs.getString("cod"), rs.getString("nombre"), rs.getDouble("precioSin"), rs.getInt("stock"), NombreCategoria);
                
                /* Redondear */
                Redondear redondear = new Redondear();
                
                Object Datos[]={p1.getCodArticulo() ,p1.getNomeArticulo(), p1.getCategoria(), p1.getStock(), p1.getPrecioSin(), p1.getIVA(), redondear.redondearDecimales(p1.getPrecioSin()+p1.getIVA()) };
                modelo.addRow(Datos);
                
            }
            
            if(cont==0){
                
                switch(PaListarProducto.salir){
                    
                    case 0:
                        errores.errorProductos PaAvisoProductos = new errores.errorProductos(new javax.swing.JDialog(), true);
                        PaAvisoProductos.setVisible(true);
                    break;
                    
                    case 1:
                        PaListarProducto.salir = 0;
                        dispose();
                    break;
                
                }
            
            }
            
        }
        catch(SQLException Ex){
            this.errores.setText("Lo sentimos no podemos conectar con la base de datos");
            System.err.println("Problemas al conectar con la DB");
        }
    }//GEN-LAST:event_formWindowOpened

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:          
    }//GEN-LAST:event_formWindowActivated

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        
        try{
            
            System.out.println("Buscando Producto con cod "+this.codigo.getText());
            
            /*Conexion contra DB*/
            db.consultas con = new db.consultas();

            /* Buscar Producto */
            ResultSet rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                
            boolean encontrado = false;
            
            while(rs.next()){
                
                if(rs.getString("cod").compareToIgnoreCase(this.codigo.getText())==0){
                    
                    VTenda.cod = this.codigo.getText();
                    
                    PaActualizarProducto PaActualizarProducto = new PaActualizarProducto(new javax.swing.JDialog(), true);
                    PaActualizarProducto.setVisible(true);
                    
                    encontrado = true;
                    
                }
            
            }
            
            this.codigo.setText("");
            
            if(encontrado == false){
                
                errores.errorCambiarProducto errorCambiarProducto = new errores.errorCambiarProducto(new javax.swing.JDialog(), true);
                errorCambiarProducto.setVisible(true);
                
            }
            
            this.codigo.setText("");
        
        }
        catch(SQLException ex){
            this.errores.setText("Lo sentimos, acabamos de sufrir un error");
            System.err.println("Error al conectar con la base de datos");
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed
        
        /*Evento para tecla ENTER*/
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{

                System.out.println("Buscando Producto con cod "+this.codigo.getText());

                /*Conexion contra DB*/
                db.consultas con = new db.consultas();

                /* Buscar Producto */
                ResultSet rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");

                boolean encontrado = false;

                while(rs.next()){

                    if(rs.getString("cod").compareToIgnoreCase(this.codigo.getText())==0){

                        VTenda.cod = this.codigo.getText();

                        PaActualizarProducto PaActualizarProducto = new PaActualizarProducto(new javax.swing.JDialog(), true);
                        PaActualizarProducto.setVisible(true);

                        encontrado = true;

                    }

                }

                this.codigo.setText("");

                if(encontrado == false){

                    errores.errorCambiarProducto errorCambiarProducto = new errores.errorCambiarProducto(new javax.swing.JDialog(), true);
                    errorCambiarProducto.setVisible(true);

                }

                this.codigo.setText("");

            }
            catch(SQLException ex){
                this.errores.setText("Lo sentimos, acabamos de sufrir un error");
                System.err.println("Error al conectar con la base de datos");
            }
        }
        
    }//GEN-LAST:event_codigoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PaListarProducto dialog = new PaListarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField codigo;
    private javax.swing.JLabel errores;
    private javax.swing.JLabel jLCodigoProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productos;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
