/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import vtenda.Redondear;
import vtenda.VTenda;

/**
 *
 * @author DAW221
 */
public class administrarProductos extends javax.swing.JDialog {
    
    /************** VARIABLES PARA UPLOAD *************************************/
    public File dir_img1;
    public File dir_img2;
    public String nombre_img="";
    public String cod_producto = "";
    public boolean segunda_img = false;
    
    /**
     * Creates new form generarClave
     */
    public administrarProductos(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Image icono = new ImageIcon(getClass().getResource(VTenda.dirIMG)).getImage();
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        errores = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        jLCodigo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jLStock = new javax.swing.JLabel();
        stock = new javax.swing.JSpinner();
        jLSinIva = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        jLImagenes = new javax.swing.JLabel();
        img1 = new javax.swing.JTextField();
        btn_img1 = new javax.swing.JButton();
        img2 = new javax.swing.JTextField();
        btn_img2 = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        categoria = new javax.swing.JComboBox<>();
        jLSinIva1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VTenda - Administrar Productos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        volver.setText("Volver");
        volver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        errores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        codigo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                codigoKeyPressed(evt);
            }
        });

        jLCodigo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLCodigo.setText("Codigo Producto:");

        jLNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLNombre.setText("Nombre Producto:");

        nombre.setEditable(false);
        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDescripcion.setText("Descripcion:");

        descripcion.setEditable(false);
        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        jLStock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLStock.setText("Stock:");

        stock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stock.setEnabled(false);

        jLSinIva.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSinIva.setText("Categoría:");

        precio.setEditable(false);
        precio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLImagenes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLImagenes.setText("Imagenes:");

        img1.setEditable(false);
        img1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_img1.setBackground(new java.awt.Color(204, 204, 204));
        btn_img1.setText("Seleccionar");
        btn_img1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_img1.setEnabled(false);
        btn_img1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_img1ActionPerformed(evt);
            }
        });

        img2.setEditable(false);
        img2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_img2.setBackground(new java.awt.Color(204, 204, 204));
        btn_img2.setText("Seleccionar");
        btn_img2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_img2.setEnabled(false);
        btn_img2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_img2ActionPerformed(evt);
            }
        });

        modificar.setBackground(new java.awt.Color(204, 204, 204));
        modificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        modificar.setText("Modificar");
        modificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        categoria.setEnabled(false);

        jLSinIva1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSinIva1.setText("Precio Sin Iva:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLImagenes)
                                    .addComponent(jLDescripcion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_img1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLStock, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(102, 102, 102))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_img2)
                                        .addGap(0, 93, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLSinIva, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLSinIva1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLCodigo))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLNombre)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(nombre)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStock, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLImagenes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLSinIva, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSinIva1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_img2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_img1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(errores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volver)
                    .addComponent(modificar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void btn_img2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_img2ActionPerformed
        buscarIMG(2);
    }//GEN-LAST:event_btn_img2ActionPerformed

    private void btn_img1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_img1ActionPerformed
        buscarIMG(1);
    }//GEN-LAST:event_btn_img1ActionPerformed

    private void codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyPressed
        
        /*Evento para tecla ENTER*/
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            
            try{
                
                db.consultas con = new db.consultas();

                ResultSet rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                
                int cont = 0;
                
                while(rs.next()){
                    
                    cont++;
                    
                    this.codigo.setEditable(false);
                    
                    this.nombre.requestFocus();
                    
                    this.nombre.setText(rs.getString("nombre"));
                    this.descripcion.setText(rs.getString("descripcion"));
                    this.stock.setValue(rs.getInt("stock"));
                    this.precio.setText((rs.getDouble("precioSin")+"").replace('.', ','));
                    this.errores.setText("");
                    
                    ResultSet categoria = con.select("categorias", "1 ORDER BY categorias.cod ASC");
                    
                    while(categoria.next()){
                        this.categoria.addItem(categoria.getString("nombre"));
                    }
                    
                    this.categoria.setSelectedIndex(rs.getInt("codCategoria"));
                    
                    this.categoria.setEnabled(true);
                    this.nombre.setEditable(true);
                    this.descripcion.setEditable(true);
                    this.stock.setEnabled(true);
                    this.precio.setEditable(true);
                    
                    this.btn_img1.setEnabled(true);
                    this.btn_img2.setEnabled(true);
                    
                }
                
                if(cont == 0){
                    this.codigo.setText("");
                    this.codigo.requestFocus();
                    this.errores.setText("El producto buscado no se encuentra.");
                }
            
            }
            catch(SQLException ex){
                System.err.println("Acabamos de sufrir un error ao buscar o cod do producto.");
                this.errores.setText("Lo sentimos, Acabamos de sufrir un error.");
            }
            
        
        }

    }//GEN-LAST:event_codigoKeyPressed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        
        try{
            
            /* Definir Conexion y ResultSet */
            db.consultas con = new db.consultas();
            ResultSet rs;
                    
            if(this.nombre.getText().isEmpty()){
                rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                while(rs.next()){
                    this.nombre.setText(rs.getString("nombre"));
                }
            }
            if(this.descripcion.getText().isEmpty()){
                rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                while(rs.next()){
                    this.descripcion.setText(rs.getString("descripcion"));
                }
            }
            if((int)this.stock.getValue() < 0){
                rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                while(rs.next()){
                    this.stock.setValue(rs.getInt("stock"));
                }
            }
            if(this.precio.getText().isEmpty()){
                rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                while(rs.next()){
                    this.precio.setText((rs.getDouble("precioSin")+"").replace('.', ','));
                }
            }
            if(this.categoria.getSelectedIndex() == 0){
                rs = con.select("productos", "cod = '"+this.codigo.getText()+"'");
                while(rs.next()){
                    this.categoria.setSelectedIndex(rs.getInt("codCategoria"));
                }
            }
            
            double precioSin = 0;
            
            try{
                
                /* Pasar texto a double */
                precioSin = Double.parseDouble(this.precio.getText().replace(',', '.'));
                
                Redondear rd = new Redondear();
                
                /* Actualizar datos */
                con.update("productos", "nombre = '"+this.nombre.getText()+"', descripcion = '"+this.descripcion.getText()+"', codCategoria = "+this.categoria.getSelectedIndex()+", precioSin = "+rd.redondearDecimales(precioSin)+",stock = "+this.stock.getValue(), "cod = '"+this.codigo.getText()+"'");
                
                // Thread para Upload IMG
                // Subir IMG
                cod_producto = this.codigo.getText().trim();
                
                if(!this.img1.getText().isEmpty()){

                    cod_producto = this.codigo.getText().trim();
                    nombre_img = this.nombre.getText().replace(' ', '_') + "_" + this.codigo.getText().trim();

                    if(!this.img2.getText().isEmpty()){
                        segunda_img = true;
                    }

                    Thread thread = new Thread(){
                        public void run(){

                            // Declarar conexion
                            db.consultas con = new db.consultas();

                            if(dir_img1.exists()){
                                SFTP.SubirIMG img1 = new SFTP.SubirIMG(nombre_img+"_1.png", dir_img1);
                                try{
                                    //Insertar nombre file
                                    con.update("productos", "img1 = '"+nombre_img+"_1.png'", "cod = '"+cod_producto+"'");
                                }
                                catch(SQLException ex){
                                    System.err.println("Error con DB al actualizar nombre IMG");
                                }
                            }
                            else{
                                System.err.println("La IMG 1 no existe");
                            }
                            if(segunda_img){
                                if(dir_img2.exists()){
                                    SFTP.SubirIMG img2 = new SFTP.SubirIMG(nombre_img+"_2.png", dir_img2);
                                    try{
                                        //Insertar nombre file
                                        con.update("productos", "img2 = '"+nombre_img+"_2.png'", "cod = '"+cod_producto+"'");
                                    }
                                    catch(SQLException ex){
                                        System.err.println("Error con DB al actualizar nombre IMG");
                                    }
                                }
                            }
                            else{
                                try{
                                    //Insertar valor nulo
                                    con.update("productos", "img2 = NULL", "cod = '"+cod_producto+"'");
                                }
                                catch(SQLException ex){
                                    System.err.println("Error con DB al actualizar nombre IMG");
                                }
                            }

                            segunda_img = false;
                            nombre_img = "";
                            cod_producto = "";

                        }
                    };

                    thread.start();
                    
                }
                else{
                    try{
                        //Insertar valor nulo
                        con.update("productos", "img1 = NULL", "cod = '"+cod_producto+"'");
                    }
                    catch(SQLException ex){
                        System.err.println("Error con DB al actualizar nombre IMG");
                    }
                }
                
                this.codigo.setEditable(true);
                this.codigo.setText("");

                this.codigo.requestFocus();

                this.nombre.setText("");
                this.descripcion.setText("");
                this.stock.setValue(0);
                this.precio.setText("");

                this.errores.setText("Producto actualizado con exito");
                
                this.categoria.setEnabled(false);
                
                int itemCount = categoria.getItemCount();
                for(int i=0;i<itemCount;i++){
                    categoria.removeItemAt(0);
                }
                this.categoria.addItem("Seleccione:");
                
                this.nombre.setEditable(false);
                this.descripcion.setEditable(false);
                this.stock.setEnabled(false);
                this.precio.setEditable(false);

                this.btn_img1.setEnabled(false);
                this.btn_img2.setEnabled(false);
                this.img1.setText("");
                this.img2.setText("");
                
            }
            catch(NumberFormatException ex){
                this.errores.setText("Introduce un precio correcto");
                System.err.println("Error al pasar a Double");
            }
             
        }
        catch(SQLException ex){
            this.errores.setText("Lo sentimos acabamos de sufrir un error");
            System.err.println("Acabamos de sufrir un error al conectar con la DB");
        }
        
    }//GEN-LAST:event_modificarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        this.categoria.addItem("Seleccione:");
        
    }//GEN-LAST:event_formWindowOpened
    
    private void buscarIMG(int numero_btn){
        
        //Mostrar la ventana para abrir archivo y recoger la respuesta
        JFileChooser fc = new JFileChooser();
        
        //Crear filtro para Imagenes 
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imágenes", "jpg", "png");
        fc.setFileFilter(filter);
                
        int respuesta = fc.showOpenDialog(this);
        
        //Comprobar si se ha pulsado Aceptar
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            
            File archivoElegido = fc.getSelectedFile();
            System.out.println("Seleccionando o archivo: "+archivoElegido);
            
            //Colocar Dir en Campo de Texto
            if(this.img1.getText().isEmpty()){
                this.img1.setText(" "+archivoElegido);
                dir_img1 = archivoElegido;
            }
            else{
                
                if(numero_btn==1){
                    this.img1.setText(" "+archivoElegido);
                    dir_img2 = archivoElegido;
                }
                else{
                    this.img2.setText(" "+archivoElegido);
                    dir_img2 = archivoElegido;
                }
            
            }
               
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                administrarProductos dialog = new administrarProductos(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_img1;
    private javax.swing.JButton btn_img2;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel errores;
    private javax.swing.JTextField img1;
    private javax.swing.JTextField img2;
    private javax.swing.JLabel jLCodigo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLImagenes;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLSinIva;
    private javax.swing.JLabel jLSinIva1;
    private javax.swing.JLabel jLStock;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JSpinner stock;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
